civicrm/org.civicrm.contactlayout

CRM/Contactlayout/Form/Inline/ProfileBlock.php, CRM/Contactlayout/Page/Inline/ProfileBlock.php, README.md, info.xml, templates/CRM/Contactlayout/Page/Inline/ProfileBlock.tpl
Fixes #22 
Now you can pick one or more employers as the "Current employer"
Now this extension actually handles the field better than core :/
We should port this functionality to core at some point, but probably will want to do one more step and have the "current employer" and "organization name" fields be serialized.
=> Handle selection of one or more employers

CRM/Contactlayout/Form/Inline/ProfileBlock.php, CRM/Contactlayout/Page/Inline/ProfileBlock.php, templates/CRM/Contactlayout/Form/Inline/ProfileBlock.tpl
This allows the "Groups" field to function as one would expect it to.
Because profiles handle groups so oddly (with all kinds of assumptions about the form being front-end-facing and requiring double-opt-in, etc) I opted to override the whole kaboodle in this extension.
Depends on https://github.com/civicrm/org.civicrm.api4/pull/95
=> Add support for 'Groups' profile field

CRM/Contactlayout/BAO/ContactLayout.php, CRM/Contactlayout/Page/Inline/ProfileBlock.php, contactlayout.php, templates/CRM/Contactlayout/Page/Inline/ProfileBlock.tpl
This makes the ajax more seamless when using profile-based blocks.
For example now if you add a "first name" and "last name" field to the profile and edit the block, the contact name at the top of the screen will update.
=> Refresh related blocks

CRM/Contactlayout/BAO/ContactLayout.php
This makes use of custom group icons, if available, per https://github.com/civicrm/civicrm-core/pull/17531
=> Use custom group icons if available

CRM/Contactlayout/BAO/ContactLayout.php, ang/contactlayout.ang.php, ang/contactlayout.css, ang/contactlayout/contactlayout.html, ang/contactlayout/contactlayout.js, ang/contactlayout/edit-block-relationship-dialog.html
This PR Adds support for displaying blocks in layouts that are meant for different contact types.
This closes https://github.com/civicrm/org.civicrm.contactlayout/issues/71
* We now provide the list of relationship types as an angular setting instead of fetching them on demand. The reason for this is that we need to have the relationship types to check if the blocks can be dragged onto the given layout. This simplifies accessing the relationship types.
*  On the front-end, the `checkBlockValidity` function determines if the block can be dragged for the given layout. This is how it works for the given scenarios:
* When the layout does not specify a contact type it will always set the block as valid.
* When the layout specifies a contact type, but the block has no relationship selected, it …
=> CATL-1529: Support for relationships between different contact types

CRM/Contactlayout/Page/Angular.php
Fixes #78 
This isn't needed in Civi 5.25+; adding to support older versions of civi.
=> Cast api4 results to array before serializing

CRM/Contactlayout/Page/Angular.php, info.xml
This makes use of the new `addBundle()` method in Civi 5.31. This breaks backward compatibility with earlier versions of Civi.
=> Add bootstrap3 bundle (requires 5.31)

CRM/Contactlayout/Helper/ProfileRelatedContact.php
To reproduce:
* Display a block for a relationship type
* Create two contacts, then create the relationship between them.
* Notice how the layout displays the relationship between the contacts
Then:
* Problem 1: Delete the other contact - the contact will still be displayed in the block.
* Problem 2: Add a new relationship to another contact - it will still display the deleted contact
=> Do not display a relationship to a deleted contact

contactlayout.php
Attempt to fix #98 
Since restricted users do not have access to `\Civi\Api4\Setting::get`, we have to skip permission checks.
As this request only retrieves the default tabs that should be fine.
=> Disable permission check to retrieve default tabs

CRM/Contactlayout/BAO/ContactLayout.php, info.xml
The new 'groups' api filter works with smart groups as well as group nesting.
Fixes #92
Fixes #64
Note, this depends on #20507 which will be in the CiviCRM 5.39 release.
=> Groups filter - support smart groups and nested groups

contactlayout.php
Refs #105
This doesn't solve the API4 not being able to validate the `contactlayout_default_tabs` setting (which feels like a core bug), only prevents the thrown API_Exception from crashing the contact page. I'll leave it up to the maintainer as to whether this counts as a fix.
Agileware ref CIVICRM-1835
=> Add Exception hander to avoid settings validation crash.

CRM/Contactlayout/BAO/ContactLayout.php
When a contact layout is set to filter on one or more groups, and the group is subsequently deleted, it leaves the layout in an unstable state. This catches and logs the error instead of triggering a fatal.
=> Catch and log nonexistent groups instead of a fatal error

contactlayout.php, css/contact-summary-layout.css
Adds a class to the "Layout: xx" link so that it can be more easily overridden with custom theming.
(The link is a good idea, but I ran into situations where users are admins but found it too distracting)
The specific CSS selector was to make sure it took precedence over Shoreditch CSS.
=> Add CSS class for Edit Layout, for easier theming

CRM/Contactlayout/BAO/ContactLayout.php
When a custom group has no custom fields the screen throws a fatal error on php8.1 
````
TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /home/drupal9/web/sites/default/files/civicrm/ext/org.civicrm.contactlayout/CRM/Contactlayout/BAO/ContactLayout.php on line 457 #0 /home/drupal9/web/sites/default/files/civicrm/ext/org.civicrm.contactlayout/CRM/Contactlayout/BAO/ContactLayout.php(457): in_array('133', NULL)
#1 /home/drupal9/web/sites/default/files/civicrm/ext/org.civicrm.contactlayout/CRM/Contactlayout/BAO/ContactLayout.php(386): CRM_Contactlayout_BAO_ContactLayout::addBlockRelations(Array, Object(Civi\Api4\Generic\Result), Object(Civi\Api4\Generic\Result))
#2 /home/drupal9/web/sites/default/files/civicrm/ext/org.civicrm.contactlayout/CRM/Contactlayout/ …
```
=> Fix fatal error for php8 when no custom fields in custom group

CRM/Contactlayout/BAO/ContactLayout.php, Civi/Api4/Action/ContactLayout/GetTabs.php, ang/contactlayout/contactLayoutEditTabs.component.js, ang/contactlayout/contactLayoutEditTabs.html, ang/contactlayout/contactLayoutEditor.component.js, info.xml
As of 5.57, core and Afform both now provide contact type information in block and tab hooks.
See https://github.com/civicrm/civicrm-core/pull/25101
=> Support multiple contact types for each block or tab

CRM/Contactlayout/BAO/ContactLayout.php
https://github.com/civicrm/org.civicrm.contactlayout/pull/124 added support for multiple contact types for each block or tab.  But I was seeing this error:
```
PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /home/jon/local/mysite/web/wp-content/civicrm-custom/extensions/org.civicrm.contactlayout/CRM/Contactlayout/BAO/ContactLayout.php:200"
```
That's because we were setting `$blockContentType` to `NULL` instead of an empty array, but then using it in places that required an array.  I've fixed that and tightened up the type hint.
=> blockContactType is always an array

templates/CRM/Contactlayout/Form/Inline/ProfileBlock.tpl
Fatal error on profile blocks on PHP 8.2
>TypeError: Cannot access offset of type string on string in include() (line 48 of web/sites/default/files/civicrm/templates_c/en_US/%%CC/CC2/CC20B997%%ProfileBlock.tpl.php).
This PR iterates the same fix done at https://github.com/civicrm/civicrm-core/pull/26517 & https://github.com/civicrm/civicrm-core/pull/26763
https://github.com/civicrm/org.civicrm.contactlayout/issues/142 seems like a related issue.
=> Fix fatal error on inline profile block

CRM/Contactlayout/Page/Inline/ProfileBlock.php
If you add a phone + extension in a profile and add it to you contact layout, it will display the phone with extension + the extension label as a distinct field as seen in the screenshot :+1: 
This PR removes the unecessary labels.
=> remove phone_ext as a distinct field

templates/CRM/Contactlayout/Page/Base.tpl, templates/CRM/Contactlayout/Page/Inline/ProfileBlock.tpl
Ensure translated strings don't inadvertently break out of the quotes or contain any unsupported characters.
=> Smarty - Escape all translated html attributes

info.xml
As of ?6.0? this is visible in the UI - although it is not terribly obvious - the goal is to get it added to the extensions & then start to make it more prominent / add warnings.
As it is forward-looking I haven't added php 8.0 / old Smarty versions
=> Add smarty & php compatibility info
